apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: pushme
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: gcr.io/s9-demo/kpush-server:latest
            imagePullPolicy: Always
            env:
            - name: RELEASE
              value: "v0.3.2"
            - name: KNOWN_PUBLISHER_TOKENS
              value: "t1-86b364g2c3c1879f,t2-86b448a1d4c1879f"
            - name: MSG_SIG_KEY
              value: "super-long-secret-here"